### ISSUE TITLE
small patch for build fixing

### ISSUE THREAD

**Issue by sezero** [bazilio-ua/fxquake#1]
Here is a small patch to fix build: [patch.txt](https://github.com/bazilio-ua/fxquake/files/7614059/patch.txt)

Question about macOS `cd_mac.m`: Is it well tested? Is it only for 10.5 and newer?

**Comment by bazilio-ua** [comment]
> Here is a small patch to fix build: [patch.txt](https://github.com/bazilio-ua/fxquake/files/7614059/patch.txt)

Thanks

> Question about macOS `cd_mac.m`: Is it well tested? Is it only for 10.5 and newer?

Here CoreAudio with AudioUnit is using for play CDs and resampling sfx up to 192kHz via -sndspeed
I've done it on Snow Leopard and tested on MacBook with internal SuperDrive, theoretically it should work on modern macOS with external USB SuperDrive.
I've never tested it on Leopard 10.5 and/or PPC arch.

**Comment by sezero** [comment]
Thanks. Closing.
